ProyectoIndividual/force-app/main/default/objects/Answer__c/Answer__c.object-meta.xml
<CustomObject>
    <label>Answer</label>
    <nameField>
        <displayFormat>A - {00000}</displayFormat>
        <label>Answer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProyectoIndividual/force-app/main/default/objects/Question_Response__c/Question_Response__c.object-meta.xml
<CustomObject>
    <label>Question_Response</label>
    <nameField>
        <displayFormat>QR - {0000}</displayFormat>
        <label>Question_Response</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question_Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProyectoIndividual/force-app/main/default/objects/Question_Response__c/fields/Answer__c.field-meta.xml
<CustomField>
    <fullName>Answer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Answer</label>
    <referenceTo>Answer__c</referenceTo>
    <relationshipLabel>Question_Responses</relationshipLabel>
    <relationshipName>Question_Responses</relationshipName>
    <type>Lookup</type>
</CustomField>

ProyectoIndividual/force-app/main/default/objects/Question_Response__c/fields/Unit_Response__c.field-meta.xml
<CustomField>
    <fullName>Unit_Response__c</fullName>
    <label>Unit Response</label>
    <referenceTo>Unit_Response__c</referenceTo>
    <relationshipLabel>Question_Responses</relationshipLabel>
    <relationshipName>Question_Responses</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProyectoIndividual/force-app/main/default/objects/Question_Response__c/fields/Unit_Response_Id__c.field-meta.xml
<CustomField>
    <fullName>Unit_Response_Id__c</fullName>
    <label>Unit Response Id</label>
    <referenceTo>Unit_Response__c</referenceTo>
    <relationshipLabel>Question_Responses</relationshipLabel>
    <relationshipName>Question_Responses</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProyectoIndividual/force-app/main/default/objects/Unit_Response__c/Unit_Response__c.object-meta.xml
<CustomObject>
    <label>Unit_Response</label>
    <nameField>
        <displayFormat>UR - {0000}</displayFormat>
        <label>UnitResponse</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Unit_Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProyectoIndividual/force-app/main/default/classes/UnitResponseTrigger.cls
public with sharing class UnitResponseTrigger {

    public static void onBeforeUpdate(List <Unit_Response__c> unitResponseList, Map<id, Unit_Response__c> oldUnitResponseMap) {
        
        //Creo una lista donde se guardaran las unit response que cumplan con los requisitos del for loop.
        List <Unit_Response__c> ansUnitRespList = new List <Unit_Response__c> ();

        for(Unit_Response__c unitResponse : unitResponseList){
            if(unitResponse.Status__c== 'Answered' && oldUnitResponseMap.getValue(unitResponse.id).Status__c== 'Draft'){
                ansUnitRespList.add(unitResponse);
            }
        }
    }
    //Method que verifica si las respuestas selecionadas son las correctas, si lo son, entonces el status de Unitd Response pasara a ser complete = true
    private static void validateAnswers (List <Unit_Response__c> unitResponseList){

        Map <id, Unit_Response__c> dbUnitRespMap = new Map <id, Unit_Response__c>([SELECT Id, (SELECT Id, Answer__r.Is_Correct__c FROM Question_Responses__r ) FROM Unit_Response__c WHERE Id in : UnitResponseList]);

        for (Unit_Response__c unitResponse : unitResponseList){
            
            UnitResponse.Answers__r.Is_Correct__c = true;

            for(Question_Response__c questionResp : dbUnitRespMap.get(unitResponse.id).Question_Responses__r){
                if(!questionResp.Answers__r.Is_Correct__c){
                    unitResponse.Status__c = false;
                    break;
                }
            }
        }
    }

    
}